### ISSUE TITLE
How to create frames folder?

### ISSUE THREAD

**Issue by suryateja0101** [mks0601/IntegralAction_RELEASE#4]
Hi, im trying with mimetics data sets. Arranged data folder as you mentioned. 
1. But what to keep in the frames folder?? 
2. I have downloaded the mimetics dataset which has the videos. where to keep them ?
Im facing issue like this (Really need your support right now as i have project demonstration on monday)
![1](https://user-images.githubusercontent.com/93408573/173138040-c236fdfa-28c0-4879-b03b-14faa82d15ba.png)

**Comment by mks0601** [comment]
You can run tool/Mimetics/fix_invalid_name.py and run tool/Mimetics/video2image.py

**Comment by suryateja0101** [comment]
Thank you, it fixed the frames issue. i went to the next point in the code @ Training
I used the command python train.py --gpu 0-3 --mode rgb_only
and i got the memory issue, any idea how to resolve this?

![3](https://user-images.githubusercontent.com/93408573/173171599-e7af710e-b84f-4a47-b224-0b22e31833a6.png)

Google search suggests reduce batch size and all. Can you suggest what needs to be done.
